### ISSUE TITLE
AttributeError: 'YouTube' object has no attribute 'filter'

### ISSUE THREAD

**Issue by rudolphos** [AdamSpannbauer/youtube_reaction_face#1]
After video gets downloaded, this error shows up.

```
downloading yt video to tmp dir: /tmp/tmpIDpLDr
Traceback (most recent call last):
  File "yt_reaction_faces.py", line 280, in <module>
    main(sys.argv[1:])
  File "yt_reaction_faces.py", line 213, in main
    pdata, pframes, pfacedims = getNewInstances(ytURL, faceDet, faceDet2, faceDet3, faceDet4, maxCount=maxFrames)
  File "yt_reaction_faces.py", line 79, in getNewInstances
    mp4Frames(ytURL, framepath, maxCount)
  File "yt_reaction_faces.py", line 57, in mp4Frames
    downloadYtMp4(ytURL, dirpath)
  File "yt_reaction_faces.py", line 43, in downloadYtMp4
    hqMp4 = yt.filter('mp4')[-1]
AttributeError: 'YouTube' object has no attribute 'filter'
```

**Comment by AdamSpannbauer** [comment]
thanks for pointing out the issue. i haven't used the code from this repo in a while, but happy to look into it.

what version of pytube do you have installed?

```
>>> import pytube
>>> pytube.__version__
```

**Comment by AdamSpannbauer** [comment]
Here is [a gist](https://gist.github.com/AdamSpannbauer/3f4cb44417d8865cbb33dcd69243e5fd) with the code that you're error comes from.  The pytube download worked without a hitch for me. 

I'm using pytube v6.4.2 and python v2.7.13

**Comment by rudolphos** [comment]
>what version of pytube do you have installed?

**pytube 8.0.2** and Python 2.7.12

I guess that might be the problem, I will downgrade and try later.

EDIT: downgraded to 6.4.2 and it works.

**Comment by AdamSpannbauer** [comment]
I plan to eventually get back around to reworking this repo to remove the windows API dependency.  When I do I'll fix the code to use more recent pytube.

**Comment by kaduprasad** [comment]
import pytube
link = "https://www.youtube.com/watch?v=mpjREfvZiDs"
yt = pytube.YouTube(link)
stream = yt.streams.first()
stream.download(SAVE_PATH)

**Comment by BHARAT0310** [comment]
> import pytube
> link = "https://www.youtube.com/watch?v=mpjREfvZiDs"
> yt = pytube.YouTube(link)
> stream = yt.streams.first()
> stream.download(SAVE_PATH)

It is not possible to set video quality manually.

**Comment by ajaycc17** [comment]
The code below works:
```python
from pytube import YouTube
yt = YouTube('https://www.youtube.com/watch?v=MvFcY9rTPx8')
yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution')[-1].download()
```

**Comment by Infamous-Koala** [comment]
Pytube is a shit library. Change my mind
